### ISSUE TITLE
Cambiar logo Kobotoolbox y firma de Enketo

### ISSUE THREAD

**Issue by LaimeJesus** [scanterra/enketo-express#1]
### Es

* [ ] Bug Report?
* [x] Feature Request?
* [ ] Support Request ?.

### Description

Se requiere implementar los cambios pedidos en esta [tarea](https://app.clickup.com/t/3025315/EXT-150). La cuál requiere los siguientes puntos:
- [x] Cambiar el logo de `Kobotoolbox` por uno de Scanterra
- [x] Eliminar la firma de `Powered by Enketo`.

Estas aparecen al momento de crear un registro para un formulario.

**Comment by LaimeJesus** [comment]
Implementados los cambios

![image](https://user-images.githubusercontent.com/13955827/93896663-906d6000-fcc7-11ea-96d0-83249889dc1a.png)

**Comment by asassano** [comment]
@LaimeJesus dónde linkeas esta issue con la rama y/o commit que lo aplican??

**Comment by LaimeJesus** [comment]
> @LaimeJesus dónde linkeas esta issue con la rama y/o commit que lo aplican??

Se puede ver arriba, en el historial de cambios de este issue

![image](https://user-images.githubusercontent.com/13955827/93913315-48583880-fcdb-11ea-903d-0e486e2cc536.png)

**Comment by LaimeJesus** [comment]
Implementado en #2
