### ISSUE TITLE
Definir ramas del flujo de trabajo(GitFlow)

### ISSUE THREAD

**Issue by LaimeJesus** [scanterra/enketo-express#3]
Se necesitan definir las rama develop, release y master de este repositorio, de manera que se pueda continuar con el flujo de trabajo definido en Scanterra. Para esto se necesitan crear o modificar las siguientes ramas a partir de la rama develop/1.70.1, la cuál es la rama funcionando actualmente en producción.
- develop: crear una nueva a partir de `develop/1.70.1`
- release: crear una nueva a partir de `develop/1.70.1`
- master: borrar y crear una nueva a partir de `develop/1.70.1`, este paso no es necesario hacerlo ahora, pero necesitamos definir una rama que represente la última release de la aplicación en Producción.

**Comment by asassano** [comment]
@LaimeJesus algunas consultas??
> Se necesitan definir las rama develop, release y master de este repositorio, de manera que se pueda continuar con el flujo de trabajo definido en Scanterra. Para esto se necesitan crear o modificar las siguientes ramas a partir de la rama develop/1.70.1, la cuál es la rama funcionando actualmente en producción.
> 
> * develop: crear una nueva a partir de `develop/1.70.1`
OK, la prodría llamar "develop_st" o se podría dejar esta y le aplico los permisos, codeowners, etc.??
> * release: crear una nueva a partir de `develop/1.70.1`
La puedo crear a partir de la nueva "develop" anterior??
> * master: borrar y crear una nueva a partir de `develop/1.70.1`, este paso no es necesario hacerlo ahora, pero necesitamos definir una rama que represente la última release de la aplicación en Producción.
Borrar la master original de la comunidad?? no conviene nosotros nombrar una "master_st" creada a partir de nuestra "release" anterior??

**Comment by LaimeJesus** [comment]
> @LaimeJesus algunas consultas??
> 
> > Se necesitan definir las rama develop, release y master de este repositorio, de manera que se pueda continuar con el flujo de trabajo definido en Scanterra. Para esto se necesitan crear o modificar las siguientes ramas a partir de la rama develop/1.70.1, la cuál es la rama funcionando actualmente en producción.
> > 
> > * develop: crear una nueva a partir de `develop/1.70.1`
> >   OK, la prodría llamar "develop_st" o se podría dejar esta y le aplico los permisos, codeowners, etc.??
> > * release: crear una nueva a partir de `develop/1.70.1`
> >   La puedo crear a partir de la nueva "develop" anterior??

Si puede estar creada a partir de la anterior

> > * master: borrar y crear una nueva a partir de `develop/1.70.1`, este paso no es necesario hacerlo ahora, pero necesitamos definir una rama que represente la última release de la aplicación en Producción.
> >   Borrar la master original de la comunidad?? no conviene nosotros nombrar una "master_st" creada a partir de nuestra "release" anterior??

Me parece bien, nos ayudaria a mantener los repositorios lo mas parecidos a los forks

**Comment by asassano** [comment]
@LaimeJesus @cristiandley ya fueron creadas las ramas "master_st", "releas_st" y "develop_st". "develop_st" se creo de "develop/1.70.1" y de esta en orden lógico releas y master "_st".
Se aplicaron los codeowners, template y permisos de ramas. 
Lo que creo que sería prolijo es dejar "develop/1.70.1" limpia sin ningún commit adicional, osea original de como se creo del commit correspondiente y aplicar todos los PR y commit propios sobre "develop_st". Si les parecen apliquen los PR corrigiendo esto. Gracias

**Comment by LaimeJesus** [comment]
> @LaimeJesus @cristiandley ya fueron creadas las ramas "master_st", "releas_st" y "develop_st". "develop_st" se creo de "develop/1.70.1" y de esta en orden lógico releas y master "_st".
> Se aplicaron los codeowners, template y permisos de ramas.
> Lo que creo que sería prolijo es dejar "develop/1.70.1" limpia sin ningún commit adicional, osea original de como se creo del commit correspondiente y aplicar todos los PR y commit propios sobre "develop_st". Si les parecen apliquen los PR corrigiendo esto. Gracias

@asassano Te respondí en este PR. https://github.com/scanterra/enketo-express/pull/4#issuecomment-697827937

**Comment by LaimeJesus** [comment]
Definimos utilizar la rama `develop_st` como la rama por defecto para aplicar la metodologia GitFlow, como también `release_st` y `master_st`.
